# Generated by Django 5.1 on 2024-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobmodel_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Chef', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(null=True, upload_to='Media/pic')),
            ],
        ),
        migrations.DeleteModel(
            name='jobmodel',
        ),
    ]
